#!/bin/bash -eu
set -o pipefail

logPrefix="$(basename "$0")"
log() {
  echo "[$logPrefix] $*"
}

if ! sudo -n true 2>/dev/null; then
  log
  log "WARNING: sudo may be required"
  log
fi

dockerRootDir="$(docker info --format '{{print .DockerRootDir}}')"
free="$(df --output=avail "$dockerRootDir/volumes" | tail -n+2)"

containerName="central_postgres_1"
volume="$(docker inspect --format='{{(index .Mounts 0).Name}}' "$containerName")"
if [[ "$volume" = "" ]]; then
  log "!!!"
  log "!!! Volume not found for container: $containerName !!!"
  log "!!!"
  log "!!! Cannot continue !!!"
  log "!!!"
  exit 1
fi
mountpoint="$(docker volume inspect --format='{{.Mountpoint}}' "$volume")"
used="$(du -s "$mountpoint" | cut -f1)"

log
log "    Free space: $(numfmt --to=si "$((free*1000))")B"
log "Required space: $(numfmt --to=si "$((used*1000))")B"
log

if [[ "$used" -lt "$free" ]]; then
  log "You have enough space to upgrade."
  log
  log "Please follow instructions at https://docs.getodk.org/central-upgrade/"
  log
else
  log "!!!"
  log "!!! ERROR: You do not have enough space available to upgrade."
  log "!!!"
  log "!!! Increase your disk by at least $(numfmt --to=si -- "$(((used-free)*1000))")B and try again."
  log "!!!"
  log
  exit 1
fi
