name: meztlikpak-odk

services:
  pyxform:
    container_name: meztlikpak-odk-pyxform
    image: "${PYXFORM_IMAGE}"
    restart: unless-stopped
    env_file:
      - ".env"
    networks:
      - meztlikpak-odk
  
  redis_main:
    container_name: meztlikpak-odk-redis-main
    image: "${REDIS_IMAGE}"
    restart: unless-stopped
    volumes:
      - ./files/enketo/redis-enketo-main.conf:/usr/local/etc/redis/redis.conf:ro
      - redis_main:/data
    networks:
      - meztlikpak-odk
    command:
      - redis-server
      - /usr/local/etc/redis/redis.conf
  
  redis_cache:
    container_name: meztlikpak-odk-redis-cache
    image: "${REDIS_IMAGE}"
    restart: always
    volumes:
      - ./files/enketo/redis-enketo-cache.conf:/usr/local/etc/redis/redis.conf:ro
      - redis_cache:/data
    networks:
      - meztlikpak-odk
    command:
      - redis-server
      - /usr/local/etc/redis/redis.conf
  
  enketo:
    container_name: meztlikpak-odk-enketo
    build:
      context: .
      dockerfile: enketo.dockerfile
      args:
        - "IMAGE=${ENKETO_IMAGE}"
    restart: unless-stopped
    env_file:
      - ".env"
    environment:
      - SUPPORT_EMAIL=${SYSADMIN_EMAIL}
      - HTTPS_PORT=${UPSTREAM_HTTPS_PORT:-443}
    volumes:
      - secrets:/etc/secrets
    networks:
      - meztlikpak-odk
    dns:
      - "1.1.1.1"
      - "8.8.8.8"
    depends_on:
      - redis_main
      - redis_cache
  
  server:
    container_name: meztlikpak-odk-server
    build:
      context: .
      dockerfile: server.dockerfile
      args:
        - "IMAGE=${SERVER_IMAGE}"
    restart: unless-stopped
    env_file:
      - ".env"
    environment:
      - HTTPS_PORT=${UPSTREAM_HTTPS_PORT}
    volumes:
      - secrets:/etc/secrets
      - transfer:/data/transfer
    networks:
      - meztlikpak-storage
      - meztlikpak-odk
    dns:
      - "1.1.1.1"
      - "8.8.8.8"
    depends_on:
      - pyxform
      - enketo
    command: [ "./start-odk.sh" ]
    logging:
      driver: local
  
  nginx:
    container_name: meztlikpak-odk-nginx
    build:
      context: .
      dockerfile: nginx.dockerfile
      args:
        - "SERVER_IMAGE=${SERVER_IMAGE}"
        - "NGINX_IMAGE=${NGINX_IMAGE}"
    restart: unless-stopped
    env_file:
      - ".env"
    environment:
      - "CERTBOT_EMAIL=${SYSADMIN_EMAIL}"
    volumes:
      - ./files/nginx/odk.conf.template:/usr/share/odk/nginx/odk.conf.template:ro
      - ./files/nginx/client-config.json.template:/usr/share/odk/nginx/client-config.json.template:ro
    ports:
      - "${HOST_IPV4}:${HTTP_PORT}:80"
      - "${HOST_IPV6}:${HTTP_PORT}:80"
      - "${HOST_IPV4}:${HTTPS_PORT}:443"
      - "${HOST_IPV6}:${HTTPS_PORT}:443"
    networks:
      - meztlikpak-odk
    dns:
      - "1.1.1.1"
      - "8.8.8.8"
    depends_on:
      - enketo
      - server
    healthcheck:
      test: [ "CMD-SHELL", "nc -z localhost 80 || exit 1" ]
    logging:
      driver: local
      options:
        max-file: "30"

networks:
  meztlikpak-odk:
    name: meztlikpak-odk
    driver: bridge
  meztlikpak-storage:
    external: true
    name: meztlikpak-storage

volumes:
  secrets:
    name: meztlikpak-odk-secrets
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./secrets
  transfer:
    name: meztlikpak-odk-transfer
    driver: local
  redis_main:
    name: meztlikpak-odk-redis-main
    driver: local
  redis_cache:
    name: meztlikpak-odk-redis-cache
    driver: local