# Assumption: This file will be merged by `docker compose`
#
# What it does:
# Sets profiles for each service depending on whether that 
# service is required for Central development or not.
#  
# depends_on of some services are reset using !reset custom yml tag
# nb: can't replace depends_on so we have removed all the values, ok for dev
services:
  postgres14:
    profiles:
      - central
    network_mode: host
  postgres:
    profiles:
      - none
  mail:
    profiles:
      - none
  service:
    profiles:
      - none
  nginx:
    profiles:
      - none
  pyxform:
    profiles:
      - central
    # changing port here - can't use `ports` mapping with host networking
    command: ["gunicorn", "--bind", "0.0.0.0:5001", "--workers", "5", "--timeout", "600", "--max-requests", "1", "--max-requests-jitter", "3", "main:app()"]
    network_mode: host
  secrets:
    profiles:
      - central
    volumes:
      - dev_secrets:/etc/secrets
    working_dir: /etc/secrets
    command: /bin/sh -c 'echo "s0m3v3rys3cr3tk3y" > enketo-secret && echo "this $3cr3t key is crackable" > enketo-less-secret && echo "enketorules" > enketo-api-key'
  enketo:
    profiles:
      - central
    volumes:
      - dev_secrets:/etc/secrets
    depends_on: !override
      - secrets
      - enketo_redis_main
    environment:
      - ENV=DEV
    network_mode: host
  enketo_redis_main:
    profiles:
      - central
    network_mode: host
  enketo_redis_cache:
    profiles:
      - none
volumes:
  dev_secrets: