name: Test, Build, Publish

on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      publish_image:
        description: 'Publish image to registry?'
        required: true
        type: boolean
        default: false

jobs:
  test-images:
    timeout-minutes: 10
    #needs:
    #- test-misc
    #- test-envsub
    #- test-nginx
    #- test-secrets
    #- test-service
    runs-on: ubuntu-latest # TODO matrix to run on all expected versions?
    steps:
    - uses: actions/checkout@v5
      with:
        fetch-depth: 0
        fetch-tags: true
        submodules: recursive

    #- run: ./test/check-docker-context.sh --min-size 5000 --max-size 10000 --min-count 600 --max-count 700

    - run: echo "FRONTEND_VERSION=$(docker compose config --format json | jq -r .services.nginx.build.args.FRONTEND_VERSION)" >> "$GITHUB_ENV"
    - run: |
           [[ -n "$FRONTEND_VERSION" ]] && echo "FRONTEND_VERSION: '$FRONTEND_VERSION'"

    - run: FRONTEND_BUILD_MODE=fetch ./test/test-images.sh

    # Check out the current frontend version referenced by docker-compose, as it should build OK.
    - run: |
           git clone \
               --depth 1 \
               --branch "$FRONTEND_VERSION" \
               https://github.com/alxndrsn/odk-central-frontend.git \
               client
    - run: FRONTEND_BUILD_MODE=source ./test/test-images.sh

    - if: always()
      run: docker compose logs
