name: Test

on:
  push:
  pull_request:

jobs:
  test-images:
    strategy:
      fail-fast: false
      matrix:
        x: [ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10 ]
        y: [ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10 ]
    timeout-minutes: 10
    runs-on: ubuntu-latest # TODO matrix to run on all expected versions?
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        fetch-tags: true
        submodules: recursive
    - run: ./test/check-docker-context.sh --min-size 50000 --max-size 60000 --min-count 1500 --max-count 1700
